Opset Version Converter (#1148)
* Initial version converter skeleton

* Adapter interface, more complete conversion procedure

* More fleshed out procedure for version conversion

* Added map of nodes to schemas

* Registration Mechanism complete; adapter_lookup mostly there

* Initial adapter_lookup finished

* Added opset_version handler to ir_pb_converter

* Debugging version converter and abstraction

Summary: Basic debugging, finished initial C++ implementation of
version_converter

Test Plan: Will write tests once python interface is finished

Reviewers: lufang, smessmer

Subscribers:

Tasks:

Tags:

* Fixed IR to hold a list of opset_version

* Debugging, fixes to ir

* Only compilation error: use of unique_ptr copy constructor;

* Initial version converter skeleton

* More fleshed out procedure for version conversion

* Registration Mechanism complete; adapter_lookup mostly there

* Debugging version converter and abstraction

Summary: Basic debugging, finished initial C++ implementation of
version_converter

Test Plan: Will write tests once python interface is finished

Reviewers: lufang

Subscribers:

Tasks:

Tags:

* Fixed IR to hold a list of opset_version

* Debugging, fixes to ir

* Only compilation error: use of unique_ptr copy constructor;

* Fixed map

* Fixed map

* Reverting map to be multi-layered

* Reverting map to be multi-layered

* Fixed all compilation errors in version_converter

* Fixed all compilation errors in version_converter

* Compiling successfully

* Compiling successfully

* Version Converter Python Interface - Not Yet Functional

* Resolved Python adapter compilation issue

* More cpp2py_export changes for version_converter, as well as tests

* More cpp2py_export changes for version_converter, as well as tests

* Finished initial version_converter tests

* Finished initial version_converter tests

* Added asserts to tests and overall documentation

* Refactored ConvertVersion to take OperatorSetIdProto instead of OpSetID

* Refactored ConvertVersion to take OperatorSetIdProto instead of OpSetID

* Fixed version_converter_test to catch exceptions

* Refactored VersionConverter into BaseConverter

* Refactored VersionConverter into BaseConverter

* Fixed optimize_onnx iPython test to include domain

* Fixed optimize_onnx iPython test to include domain

* Fixed uncertainty bugs in converter; not sure how to fix lack of generated object file

* Switched sscanf to atoi

* Use int64_t

* More int conversions

* More conversions to int64_t

* uint64_t

* Added Version Converter to PythonAPIOverview

* Python annotations

* Changed indices to unsigned int instead of uint64_t; may introduce problems with size

* Added version_converter stub

* Lint Fixes for Travis Build

* Adapt now takes a node

* Addressed first round of code review except intermediate refactoring

* i hate ints

* Better constructor?

* Due to char*, use strcmp instead of ==

* Lots of refactoring to address Junjies comments

* IntraDomainConverter refactor

* Fixed version_converter stub

* Fixed version_converter stub

* Confusion about unique pointers and maps of const and undefined classes

* Documentation?

* Current version of our const bug

* Random changes

* Back to explicit constructor

* Fixes to Sebastian's comments

* Finished addressing Sebastian's recommendations'

* Fixed build problem with const references

* Addressing Lu comments on this branch

* Fixed version_converter initialization

* int64_t error in OpSetID constructor

* Another int64_t issue in incrementVersion

* Removed direct calls to barf

* Adjust Python docs, atoi to stoi

* fromString instead of string constructor

* No need for int64_t&

* Removed ONNX_NAMESPACE references

* No need for _visit_all_nodes_recursive

* Made test_backwards_incompatible actually backwards incompatible

* Fixed documentation for version_converter.py

* End of namespace comments

* Removed DEBUG flag from DefaultVersionConverter

* More code review fixes

* Move semantics

* Addressed Lu code review, started on NoPreviousVersionAdapter

* Need to check on adapters

* checking on adapters

* Fixed Adapter Interface and Cos Tests

* Addressed Sebastian's Comments

* Added comments to address Lu concerns

* Renamed opset_versions getter

* Removed all remaining ONNX_NAMESPACE references; not sure about strcmps

* Removed str_cmp

* Initial changes per Lu suggestions; still finishing automated NoPreviousVersionAdapter detection

* Getting new search from adapters

* Getting up from adapters

* Debug statements

* Added condition to verify defined op_name

* Removed tags

* Changed reference semantics per Sebastian suggestions

* No Previous Version rename

* Finished addressing Lu comments