Serialization for Sequence and Map data types (#2581)
* progress towards test case

* update key names so value element does not have redundancy problems

* account for position optional input in test

* fix cmake errors by removing uint8/int8 and uint16/int16 incompatible types

* fixing test case

* remove axis attribute in np.vstack to fix CI

* fix key representation as per tensorproto

* added optional to keytypes

* removing packed=true

* updating reference implementation for sequence_insert

* fixing flake8 errors in CI

* add mapping for MapProto, enhanced helper functions

* fix typing issue

* updating imports

* accounting for sequences in value_info_proto

* adjusting mapping with KeyValuePair index

* adding NP_TYPE_TO_MAP_KEY_TYPE mapping

* include kv_pair helper function

* LGTM: unused import fix, addressing sequence_value_info, generate_data temp error

* sequence as array input

* updating data forms according to setup.py CI errors

* addressing key storage

* fixing LGTM commit error

* add to_array_from_sequence

* addressing sequence case, adding more np helper functions

* add support for maps

* fixing minor syntax error

* fixing error in appveyor CI with type checks

* addressing a few CI errors upon gen_doc

* addressing typecheck errors

* address error in AttributeError: 'str' object has no attribute 'dtype'

* moving KVPair from MapProto, addressing numpy_helper SparseTensor support

* address mapping errors

* fixing CI errors w/ mapping

* fixing more minor typecheck bugs

* update sequence insert test to use lists

* addressing sequences as lists in input / output generation

* edit helper functions to address lists instead of np.arrays

* adressing list in from sequence to list functions

* temporary updates for sequence_value_info

* adding numpy dependency in cmd_tools

* address iterable nature of shape

* use abc comparisons instead of isinstance with list / dict

* last chance -> abc.Mapping / abc.Sequence

* fixing error message

* adding details to error message in cmd tools

* Updating sequence insert in the docs w/o committing from remote vm

* removing mapping for sequence/map type and instead using tensor type mappings

* removing abc.Mapping and abc.sequence

* adding gtests for c++ api test

* deprecate travis

* adding the build badges for the new pipelines in Azure, deprecating travis build badge, renaming circleCI badge

* updating badge label

* removing - in badge names

* c++ api changes for linux

* Update Linux-CI.yml for Azure Pipelines

* Update Linux-CI.yml for Azure Pipelines

* Update Linux-CI.yml for Azure Pipelines

* Update Linux-CI.yml for Azure Pipelines

* more build options

* updating testcoverage documentation

* adding the onnx-data.in.proto, removing onnx.in.proto

* updating gen_proto file to include new onnx-data proto

* update helper.py to generate proto files

* removing unecessary import

* commenting out helper functions to figure out import

* adding the onnx-data proto and onnx-data proto3 generated files

* revert commented changes to helper / np_helper

* fixing unused import by restoring relevant helper functions

* adding onnx-data-ml.proto3 files

* fixing import proto

* add onnx-data_pb.h

* add suggested fixes for import

* adding gen_onnx_data_proto in the right place

* remove all changes in onnx.in.proto

* fixing whitespace issue in flake8

* remove value_type in KeyValuePair, add relevant mapping pairings, update np helper functions

* fix constant case for tensor representation

* fixing AttributeError

* update onnx data proto files

* using getattr and copyfrom instead of setattr, fixing typing in helper.py

* removing numpy - unecessary dependency

* fixing typing errors

* adding [Any] tags for typecheck

* update documentation

* update wording

* updates to sequence_insert.py according to review comments

* fixing list syntax

* sequence insert tests

* sequence_insert test data

* updated Test Coverage

* updating operator docs

* fix typing, test is now working!

* update ordering of import statements, retrigger CI

* update shape of seq_value_info to none

* updating generated test data with new shape denotations

* addressing typing warnings

* progress towards accounting for Sequence and Map input data in driver_test.cc

* adding check for tensorproto

* merge conflicts

* update checker, test input_info

* fix warnings in checker

* fix some test_driver.cc errors

* onnx-data_pb import

* reverting unecessary changes to CI

* re-add the -y flag in MacOS CI

* restoring travis yml file

* fixing parentheses

* fixing parens

* fixing comparison errors

* fixing output and dependencies to fix errors

* fixing paren

* paren

* experimenting with typing

* update data types

* update typing

* fixing naming

* add outputs

* parens

* fixing flake8 error

* fix flake 8

* check sequence and map

* getting rid of context argument

* fix suggestions

* test new classes in comparison

* update mypy typedef

* update functions for type check as per rama's suggestion

* test path

* one more test for path

* remove tensor checks

* remove testing statements

* making checker functions more robust

* fixing errors, declaring helper functions check_kv_pair and check_seq_map_elem

* minor bug

* adding proto files

* update checker helpers with enforce_has_field functions

* fixing minor ; errors

* one last ;

* Removing SeqMapElement, KVPair, refactoring MapProto and SequenceProto

* fix lgtm errors

* fix function names

* update proto generated

* remove onnx-data-ml

* update files for repeated int / repeated byte structure

* specify in gen_proto.py to not generate onnx-data-ml.proto files

* removing "enforce_has_field" checks in sequence to account for 0 tensor case

* fix cmake to address compiler error in onnx-data

* fixing proto errors with "optional" and "repeated"

* fix imports

* add import_ml fix for gen_proto.py so that the correct imported versions appear in the newly generated protos

* update comment explanation in CMake and onnx checker for mapproto

* fixing flake8 errors

* address empty list possibility in from_list

* spacing!

* remove unused strings in test_driver

* make tensor (np.ndarray) default type option if no type is specified / no elements present in list

* missing paren

* don't need redundant make_sequence / make_map call

* fix mapping for python -> Sequence tensors / map / sequence input

* fixing whitespace

* fix numpy_helper function

* fixing type check

* fix check for dtype

* fix mapping

* see if using extend instead of append fixes problem

* simple checks - try to gen data

* update additional checks

* regenerate test data

* adding TODO for Rama's comment

* fix type check

* update protos and type check helper functions

* typecheck updates

* more typecheck fixes

* fix more typecheck

* fix key_list type

* type annotation

* try cast to list

* remove key_list initialization

* convert sequence to list

* list_any

* update protos

* ONNX_ML version of onnx-data proto

* exclude onnx-data.proto ML version in Travis git diff check

* update script for travis

* remove value_type from MapProto

* add more descriptive comments regarding maps and sequences, address comment

* add lite_proto to generated checked in protos

* whitespace in generated file